export const ALBUM_GET_REQUEST='ALBUM_GET_REQUEST'
export const ALBUM_GET_SUCCESS='ALBUM_GET_SUCCESS'
export const ALBUM_GET_FAIL='ALBUM_GET_FAIL'

export const SET_ALBUM_NAME='SET_ALBUM_NAME'
export const SET_ALBUM_NAME_FAIL='SET_ALBUM_NAME_FAIL'
