export const IMAGES_GET_REQUEST='IMAGES_GET_REQUEST'
export const IMAGES_GET_SUCCESS='IMAGES_GET_SUCCESS'
export const IMAGES_GET_FAIL='IMAGES_GET_FAIL'

export const IMAGE_GET_REQUEST='IMAGE_GET_REQUEST'
export const IMAGE_GET_SUCCESS='IMAGE_GET_SUCCESS'
export const IMAGE_GET_FAIL='IMAGE_GET_FAIL'

export const GET_USER_IMAGES_REQUEST='GET_USER_IMAGES_REQUEST'
export const GET_USER_IMAGES_SUCCESS='GET_USER_IMAGES_SUCCESS'
export const GET_USER_IMAGES_FAILED='GET_USER_IMAGES_FAILED'
